import type { Address } from "viem";

export const BALLOTBOX_ADDRESS: Address = import.meta.env
  .VITE_CONTRACT_ADDRESS as `0x${string}`;

export const BALLOTBOX_ABI = [
  { inputs: [], name: "AlreadyVoted", type: "error" },
  { inputs: [], name: "DescriptionTooLong", type: "error" },
  { inputs: [], name: "EmptyDescription", type: "error" },
  { inputs: [], name: "EmptyTitle", type: "error" },
  { inputs: [], name: "InvalidDeadline", type: "error" },
  { inputs: [], name: "ProposalExpired", type: "error" },
  { inputs: [], name: "ProposalNotActive", type: "error" },
  { inputs: [], name: "ProposalNotFound", type: "error" },
  { inputs: [], name: "TitleTooLong", type: "error" },
  { inputs: [], name: "VoteCountOverflow", type: "error" },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "author",
        type: "address",
      },
      { indexed: false, internalType: "string", name: "title", type: "string" },
      {
        indexed: false,
        internalType: "uint32",
        name: "deadline",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "detailsHash",
        type: "bytes32",
      },
    ],
    name: "ProposalCreated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "voter",
        type: "address",
      },
      { indexed: false, internalType: "bool", name: "vote", type: "bool" },
    ],
    name: "VoteCast",
    type: "event",
  },
  {
    inputs: [],
    name: "MAX_DESCRIPTION_LENGTH",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_TITLE_LENGTH",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_title", type: "string" },
      { internalType: "string", name: "_description", type: "string" },
      { internalType: "bytes32", name: "_detailsHash", type: "bytes32" },
      { internalType: "uint32", name: "_deadline", type: "uint32" },
    ],
    name: "createProposal",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_author", type: "address" }],
    name: "getAuthorProposalCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalId", type: "uint256" }],
    name: "getProposal",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "author", type: "address" },
          { internalType: "uint96", name: "yesVotes", type: "uint96" },
          { internalType: "uint96", name: "noVotes", type: "uint96" },
          { internalType: "uint32", name: "createdAt", type: "uint32" },
          { internalType: "uint32", name: "deadline", type: "uint32" },
          { internalType: "bool", name: "active", type: "bool" },
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "bytes32", name: "detailsHash", type: "bytes32" },
        ],
        internalType: "struct BallotBox.Proposal",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_author", type: "address" }],
    name: "getProposalIdsByAuthor",
    outputs: [{ internalType: "uint256[]", name: "", type: "uint256[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_offset", type: "uint256" },
      { internalType: "uint256", name: "_limit", type: "uint256" },
    ],
    name: "getProposals",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "author", type: "address" },
          { internalType: "uint96", name: "yesVotes", type: "uint96" },
          { internalType: "uint96", name: "noVotes", type: "uint96" },
          { internalType: "uint32", name: "createdAt", type: "uint32" },
          { internalType: "uint32", name: "deadline", type: "uint32" },
          { internalType: "bool", name: "active", type: "bool" },
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "bytes32", name: "detailsHash", type: "bytes32" },
        ],
        internalType: "struct BallotBox.Proposal[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_author", type: "address" },
      { internalType: "uint256", name: "_offset", type: "uint256" },
      { internalType: "uint256", name: "_limit", type: "uint256" },
    ],
    name: "getProposalsByAuthor",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "id", type: "uint256" },
          { internalType: "address", name: "author", type: "address" },
          { internalType: "uint96", name: "yesVotes", type: "uint96" },
          { internalType: "uint96", name: "noVotes", type: "uint96" },
          { internalType: "uint32", name: "createdAt", type: "uint32" },
          { internalType: "uint32", name: "deadline", type: "uint32" },
          { internalType: "bool", name: "active", type: "bool" },
          { internalType: "string", name: "title", type: "string" },
          { internalType: "string", name: "description", type: "string" },
          { internalType: "bytes32", name: "detailsHash", type: "bytes32" },
        ],
        internalType: "struct BallotBox.Proposal[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTotalProposals",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalId", type: "uint256" },
      { internalType: "address", name: "_voter", type: "address" },
    ],
    name: "getVote",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalId", type: "uint256" },
      { internalType: "address", name: "_voter", type: "address" },
    ],
    name: "hasVoted",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_proposalId", type: "uint256" }],
    name: "isProposalOpen",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "proposalCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "proposals",
    outputs: [
      { internalType: "uint256", name: "id", type: "uint256" },
      { internalType: "address", name: "author", type: "address" },
      { internalType: "uint96", name: "yesVotes", type: "uint96" },
      { internalType: "uint96", name: "noVotes", type: "uint96" },
      { internalType: "uint32", name: "createdAt", type: "uint32" },
      { internalType: "uint32", name: "deadline", type: "uint32" },
      { internalType: "bool", name: "active", type: "bool" },
      { internalType: "string", name: "title", type: "string" },
      { internalType: "string", name: "description", type: "string" },
      { internalType: "bytes32", name: "detailsHash", type: "bytes32" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "", type: "address" },
      { internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "proposalsByAuthor",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_proposalId", type: "uint256" },
      { internalType: "bool", name: "_vote", type: "bool" },
    ],
    name: "vote",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "", type: "uint256" },
      { internalType: "address", name: "", type: "address" },
    ],
    name: "votes",
    outputs: [
      { internalType: "bool", name: "hasVoted", type: "bool" },
      { internalType: "bool", name: "vote", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;
