// Component exports for cleaner imports
export { default as AuthorChip } from './AuthorChip'
export { default as InfoSection } from './InfoSection'
export { default as MyProposalCard } from './MyProposalCard'
export { default as Navbar } from './Navbar'
export { default as Pagination } from './Pagination'
export { default as ProposalCard } from './ProposalCard'
export { default as ProposalContent } from './ProposalContent'
export { default as ProposalsList } from './ProposalsList'
export { default as RelativeTime } from './RelativeTime'
export { default as SearchSection } from './SearchSection'
export { default as StatusPill } from './StatusPill'
export { default as VotingCard } from './VotingCard'
export { default as VotingStats } from './VotingStats'
